### ISSUE TITLE
Game view is inverted

### ISSUE THREAD

**Issue by chrismeteu** [Unity-Technologies/Onslaught#1]
while in the editor and after hiting play, the camera appears to be rotating correctly however in my MR headset (Lenovo Explorer) the image is inverted. is there a setting i'm missing? i am using Unity 2018.3.0f1

**Comment by draj0** [comment]
It's something to do with Light Weight rendering Pipeline (LWP). I removed it using package manager, and scene is no more inverted. However, all materials show as pink now

**Comment by MubasshirAhmed** [comment]
In daydream, controller position tracking not working. Its only rotating along with tracker.

**Comment by jackpr-unity** [comment]
@MubasshirAhmed daydream controllers only track rotation.  This is correct.

@chrismeteu there are spurious y-flip problems.  Try on a newer version of the editor.  I think we have them all sorted out now.

@dvr707 your mileage may vary with LWRP in VR.  It's still in preview.  Look out for a 19.1 update to this project in the next week or so, where I will get LWRP back on track.

**Comment by jackpr-unity** [comment]
@chrismeteu @dvr707 I've confirmed that wmr renders right side up in 2019.1.0b7.  You could try a more recent version of 2018.3 as well for a fix.

and sorry for taking so long to reply!  Apparently I wasn't set to receive notifications from my own repo 
¯\_(ツ)_/¯
