### ISSUE TITLE
Is it currently possible to use input abstraction for swipes?

### ISSUE THREAD

**Issue by aaornrylow** [Unity-Technologies/Onslaught#2]
For example a left swipe on Daydream / Oculus touchpads could be abstracted to DpadLeft the way it is in OVRInput, and that could also include the left arrow key on Windows, pressing left on a joystick on Rift / other gamepads, etc.

**Comment by jackpr-unity** [comment]
Assets/Scripts/InputAbstraction.cs is your entry point for this.  You can change that code to trigger on whatever you would like.
