### ISSUE TITLE
Daydream Eyes Wrong

### ISSUE THREAD

**Issue by lunarcloud** [Unity-Technologies/Onslaught#4]
Maybe swapped?

This might have to do with https://issuetracker.unity3d.com/issues/xr-lwrp-stereo-separation-of-eye-textures-is-incorrect-when-using-daydream-slash-cardboard 

But it's dizzying unless you close either eye.

**Comment by lunarcloud** [comment]
If I rip out the Lightweight Render Pipeline preview, (and switch the renderers to standard) then it works!

**Comment by jackpr-unity** [comment]
What editor version, platform, and commit of this project did you use?

**Comment by lunarcloud** [comment]
Unity 2018.3.8f1 
Windows
bb24f64

**Comment by jackpr-unity** [comment]
Ah yes, LWRP is exiting preview soon (if not right now) - so there were breaking changes between the package code and engine code in 2018.3.  The 2018.3 STW release targeted a 2018.3 beta.  There's probably a version of the package that will work with 2018.3.8f1, but removing LWRP and reverting the materials to the standard shader will work too.  I plan to add LWRP back to the head/2019.1 version of the project after arfoundation is updated to work with the latest lwrp.

**Comment by jackpr-unity** [comment]
I've added the following disclaimer to the readme.  Thanks for checking out this project!

"This project is made as a part of "Scenario Test Week" - a time during the beta period of our editor release cycle when we do exploratory testing by making games.  As such, releases will target beta versions of the editor and use experimental APIs. Your mileage may vary using this project with a different version of the editor than the one the project targets."
