### ISSUE TITLE
 compile error namespace 'ARExtensions' does not exist

### ISSUE THREAD

**Issue by foster991** [Unity-Technologies/Onslaught#5]
Opening project in 2019.2.0f1: type or namespace name 'ARExtensions' does not exist in the namespace 'UnityEngine.XR' . I think ARFoundation 1.2.1 removes ARExtensions altogether?
If you downgrade to 1.5.0 then ARExtension error is gone but creates new error: The type or namespace name 'SpatialTracking' does not exist
If I downgrade everything toi get rid of SpatialTraqcking error, it gives a com pile error "Library\PackageCache\com.unity.xr.arkit@1.0.0-preview.23\Runtime\FaceTracking\ARKitFaceSubsystem.cs(15,18): error CS0534: 'ARKitFaceSubsystem' does not implement inherited abstract member 'Subsystem.running.get'"

**Comment by jackpr-unity** [comment]
Hi foster,

I think the right way forward with this is to update the code to work with the latest ARFoundation.  I've had a talk with the folks here, and it appears a migration guide is included in the ARFoundation documentation (accessible through the package manager).  I'll see about putting out a release with the necessary changes.

**Comment by jackpr-unity** [comment]
The master branch is now updated for 2019.2.2f1.  I've also put out a 2019.2 release.
